
import Navbar from '@/components/Navbar'
import './globals.css'
import Banner from '@/components/Banner'
import Footer from '@/components/Footer'





  title: 'barbaar tech'
  description: 'Generated by create next app'


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Navbar/>
        {children}
        <Banner/>
        <Footer/>
      </body>
    </html>
  )
}
